# Book settings
title: "dMRI Analyses"
author: TIGRLab
copyright: "2021"

# Execution settings
execute:
  timeout: 300
  execute_notebooks: auto

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab

repository:
  url: https://github.com/tigrlab/dmri_analyses
  path_to_book: docs
  branch: main
